import type { Metadata } from "next";
import Navigation from "@/components/Sections/Nav/Navigation";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='body bg_primary text-text-color overflow-x-hidden'><Navigation/>{children}</body>
    </html>
  );
}
